#FROM sys-hursleyreleng-team-docker-local.artifactory.swg-devops.com/ubi8-base:latest
#USER root
#ADD installer /work/
#RUN chmod 755 /work/installer
#RUN /work/installer -i silent -DLICENSE_ACCEPTED=true >/tmp/installer.log 2>&1
#RUN echo "CICS TG is installed, please check the install logs"
#RUN rm -rf /work/installer

FROM openjdk:latest
RUN mkdir /work/
COPY ctgsamples.jar ctgclient.jar ctgserver.jar /work/
COPY EciB2.java EciB3.java /work/
#ENV CLASSPATH=/work/:/work/ctgclient.jar
WORKDIR /work/
#RUN javac /work/EciB2.java
COPY runAppl.sh /work/
RUN chmod 0777 /work/runAppl.sh
#ENTRYPOINT [ "/work/runAppl.sh" ]  
#CMD ["java", "EciB2 jgate=tcp://$jgate jgateport=$2 server=$3 prog0=$4 COMMAREAlength=$5"]

